-- Exercise library seed from exercises-dataset-main (generated, do not hand-edit).
-- Idempotent: ON CONFLICT (name) DO NOTHING.

INSERT INTO exercises (name, body_part, equipment, target) VALUES
('3/4 sit-up', 'waist', 'body weight', 'abs'),
('45° side bend', 'waist', 'body weight', 'abs'),
('air bike', 'waist', 'body weight', 'abs'),
('all fours squad stretch', 'upper legs', 'body weight', 'quads'),
('alternate heel touchers', 'waist', 'body weight', 'abs'),
('alternate lateral pulldown', 'back', 'cable', 'lats'),
('ankle circles', 'lower legs', 'body weight', 'calves'),
('archer pull up', 'back', 'body weight', 'lats'),
('archer push up', 'chest', 'body weight', 'pectorals'),
('arm slingers hanging bent knee legs', 'waist', 'body weight', 'abs'),
('arm slingers hanging straight legs', 'waist', 'body weight', 'abs'),
('arms apart circular toe touch (male)', 'upper legs', 'body weight', 'glutes'),
('arms overhead full sit-up (male)', 'waist', 'body weight', 'abs'),
('assisted chest dip (kneeling)', 'chest', 'leverage machine', 'pectorals'),
('assisted hanging knee raise', 'waist', 'assisted', 'abs'),
('assisted hanging knee raise with throw down', 'waist', 'assisted', 'abs'),
('assisted lying calves stretch', 'lower legs', 'assisted', 'calves'),
('assisted lying glutes stretch', 'upper legs', 'assisted', 'glutes'),
('assisted lying gluteus and piriformis stretch', 'upper legs', 'assisted', 'glutes'),
('assisted lying leg raise with lateral throw down', 'waist', 'assisted', 'abs'),
('assisted lying leg raise with throw down', 'waist', 'assisted', 'abs'),
('assisted motion russian twist', 'waist', 'medicine ball', 'abs'),
('assisted parallel close grip pull-up', 'back', 'leverage machine', 'lats'),
('assisted prone hamstring', 'upper legs', 'assisted', 'hamstrings'),
('assisted prone lying quads stretch', 'upper legs', 'assisted', 'quads'),
('assisted prone rectus femoris stretch', 'waist', 'assisted', 'abs'),
('assisted pull-up', 'back', 'leverage machine', 'lats'),
('assisted seated pectoralis major stretch with stability ball', 'chest', 'assisted', 'pectorals'),
('assisted side lying adductor stretch', 'upper legs', 'assisted', 'adductors'),
('assisted sit-up', 'waist', 'assisted', 'abs'),
('assisted standing chin-up', 'back', 'leverage machine', 'lats'),
('assisted standing pull-up', 'back', 'leverage machine', 'lats'),
('assisted standing triceps extension (with towel)', 'upper arms', 'assisted', 'triceps'),
('assisted triceps dip (kneeling)', 'upper arms', 'leverage machine', 'triceps'),
('assisted wide-grip chest dip (kneeling)', 'chest', 'leverage machine', 'pectorals'),
('astride jumps (male)', 'cardio', 'body weight', 'cardiovascular system'),
('back and forth step', 'cardio', 'body weight', 'cardiovascular system'),
('back extension on exercise ball', 'back', 'stability ball', 'spine'),
('back lever', 'back', 'body weight', 'upper back'),
('back pec stretch', 'back', 'body weight', 'lats'),
('backward jump', 'upper legs', 'body weight', 'quads'),
('balance board', 'upper legs', 'body weight', 'quads'),
('band alternating biceps curl', 'upper arms', 'band', 'biceps'),
('band alternating v-up', 'waist', 'band', 'abs'),
('band assisted pull-up', 'back', 'band', 'lats'),
('band assisted wheel rollerout', 'waist', 'band', 'abs'),
('band bench press', 'chest', 'band', 'pectorals'),
('band bent-over hip extension', 'upper legs', 'band', 'glutes'),
('band bicycle crunch', 'waist', 'band', 'abs'),
('band close-grip pulldown', 'back', 'band', 'lats'),
('band close-grip push-up', 'upper arms', 'band', 'triceps'),
('band concentration curl', 'upper arms', 'band', 'biceps'),
('band fixed back close grip pulldown', 'back', 'band', 'lats'),
('band fixed back underhand pulldown', 'back', 'band', 'lats'),
('band front lateral raise', 'shoulders', 'band', 'delts'),
('band front raise', 'shoulders', 'band', 'delts'),
('band hip lift', 'upper legs', 'band', 'glutes'),
('band horizontal pallof press', 'waist', 'band', 'abs'),
('band jack knife sit-up', 'waist', 'band', 'abs'),
('band kneeling one arm pulldown', 'back', 'band', 'lats'),
('band kneeling twisting crunch', 'waist', 'band', 'abs'),
('band lying hip internal rotation', 'upper legs', 'band', 'glutes'),
('band lying straight leg raise', 'waist', 'band', 'abs'),
('band one arm overhead biceps curl', 'upper arms', 'band', 'biceps'),
('band one arm single leg split squat', 'upper legs', 'band', 'quads'),
('band one arm standing low row', 'back', 'band', 'upper back'),
('band one arm twisting chest press', 'chest', 'band', 'pectorals'),
('band one arm twisting seated row', 'back', 'band', 'upper back'),
('band pull through', 'upper legs', 'band', 'glutes'),
('band push sit-up', 'waist', 'band', 'abs'),
('band reverse fly', 'shoulders', 'band', 'delts'),
('band reverse wrist curl', 'lower arms', 'band', 'forearms'),
('band seated hip internal rotation', 'upper legs', 'band', 'glutes'),
('band seated twist', 'waist', 'band', 'abs'),
('band shoulder press', 'shoulders', 'band', 'delts'),
('band shrug', 'back', 'band', 'traps'),
('band side triceps extension', 'upper arms', 'band', 'triceps'),
('band single leg calf raise', 'lower legs', 'band', 'calves'),
('band single leg reverse calf raise', 'lower legs', 'band', 'calves'),
('band single leg split squat', 'upper legs', 'band', 'quads'),
('band squat', 'upper legs', 'band', 'glutes'),
('band squat row', 'upper legs', 'band', 'glutes'),
('band standing crunch', 'waist', 'band', 'abs'),
('band standing rear delt row', 'shoulders', 'band', 'delts'),
('band standing twisting crunch', 'waist', 'band', 'abs'),
('band step-up', 'upper legs', 'band', 'glutes'),
('band stiff leg deadlift', 'upper legs', 'band', 'glutes'),
('band straight back stiff leg deadlift', 'upper legs', 'band', 'glutes'),
('band straight leg deadlift', 'back', 'band', 'spine'),
('band twisting overhead press', 'shoulders', 'band', 'delts'),
('band two legs calf raise - (band under both legs) v. 2', 'lower legs', 'band', 'calves'),
('band underhand pulldown', 'back', 'band', 'lats'),
('band v-up', 'waist', 'band', 'abs'),
('band vertical pallof press', 'waist', 'band', 'abs'),
('band wrist curl', 'lower arms', 'band', 'forearms'),
('band y-raise', 'shoulders', 'band', 'delts'),
('barbell alternate biceps curl', 'upper arms', 'barbell', 'biceps'),
('barbell bench front squat', 'upper legs', 'barbell', 'quads'),
('barbell bench press', 'chest', 'barbell', 'pectorals'),
('barbell bench squat', 'upper legs', 'barbell', 'quads'),
('barbell bent arm pullover', 'back', 'barbell', 'lats'),
('barbell bent over row', 'back', 'barbell', 'upper back'),
('barbell biceps curl (with arm blaster)', 'upper arms', 'barbell', 'biceps'),
('barbell clean and press', 'upper legs', 'barbell', 'quads'),
('barbell clean-grip front squat', 'upper legs', 'barbell', 'glutes'),
('barbell close-grip bench press', 'upper arms', 'barbell', 'triceps'),
('barbell curl', 'upper arms', 'barbell', 'biceps'),
('barbell deadlift', 'upper legs', 'barbell', 'glutes'),
('barbell decline bench press', 'chest', 'barbell', 'pectorals'),
('barbell decline bent arm pullover', 'back', 'barbell', 'lats'),
('barbell decline close grip to skull press', 'upper arms', 'barbell', 'triceps'),
('barbell decline pullover', 'chest', 'barbell', 'pectorals'),
('barbell decline wide-grip press', 'chest', 'barbell', 'pectorals'),
('barbell decline wide-grip pullover', 'back', 'barbell', 'lats'),
('barbell drag curl', 'upper arms', 'barbell', 'biceps'),
('barbell floor calf raise', 'lower legs', 'barbell', 'calves'),
('barbell front chest squat', 'upper legs', 'barbell', 'glutes'),
('barbell front raise', 'shoulders', 'barbell', 'delts'),
('barbell front raise and pullover', 'chest', 'barbell', 'pectorals'),
('barbell front squat', 'upper legs', 'barbell', 'glutes'),
('barbell full squat', 'upper legs', 'barbell', 'glutes'),
('barbell full squat (back pov)', 'upper legs', 'barbell', 'glutes'),
('barbell full squat (side pov)', 'upper legs', 'barbell', 'glutes'),
('barbell full zercher squat', 'upper legs', 'barbell', 'glutes'),
('barbell glute bridge', 'upper legs', 'barbell', 'glutes'),
('barbell glute bridge two legs on bench (male)', 'upper legs', 'barbell', 'glutes'),
('barbell good morning', 'upper legs', 'barbell', 'hamstrings'),
('barbell guillotine bench press', 'chest', 'barbell', 'pectorals'),
('barbell hack squat', 'upper legs', 'barbell', 'glutes'),
('barbell high bar squat', 'upper legs', 'barbell', 'glutes'),
('barbell incline bench press', 'chest', 'barbell', 'pectorals'),
('barbell incline close grip bench press', 'upper arms', 'barbell', 'triceps'),
('barbell incline reverse-grip press', 'upper arms', 'barbell', 'triceps'),
('barbell incline row', 'back', 'barbell', 'upper back'),
('barbell incline shoulder raise', 'chest', 'barbell', 'serratus anterior'),
('barbell jefferson squat', 'upper legs', 'barbell', 'glutes'),
('barbell jm bench press', 'upper arms', 'barbell', 'triceps'),
('barbell jump squat', 'upper legs', 'barbell', 'glutes'),
('barbell lateral lunge', 'upper legs', 'barbell', 'glutes'),
('barbell low bar squat', 'upper legs', 'barbell', 'glutes'),
('barbell lunge', 'upper legs', 'barbell', 'glutes'),
('barbell lying back of the head tricep extension', 'upper arms', 'barbell', 'triceps'),
('barbell lying close-grip press', 'upper arms', 'barbell', 'triceps'),
('barbell lying close-grip triceps extension', 'upper arms', 'barbell', 'triceps'),
('barbell lying extension', 'upper arms', 'barbell', 'triceps'),
('barbell lying lifting (on hip)', 'upper legs', 'barbell', 'glutes'),
('barbell lying preacher curl', 'upper arms', 'barbell', 'biceps'),
('barbell lying triceps extension', 'upper arms', 'barbell', 'triceps'),
('barbell lying triceps extension skull crusher', 'upper arms', 'barbell', 'triceps'),
('barbell narrow stance squat', 'upper legs', 'barbell', 'glutes'),
('barbell one arm bent over row', 'back', 'barbell', 'upper back'),
('barbell one arm floor press', 'upper arms', 'barbell', 'triceps'),
('barbell one arm side deadlift', 'upper legs', 'barbell', 'glutes'),
('barbell one arm snatch', 'shoulders', 'barbell', 'delts'),
('barbell one leg squat', 'upper legs', 'barbell', 'quads'),
('barbell overhead squat', 'upper legs', 'barbell', 'quads'),
('barbell palms down wrist curl over a bench', 'lower arms', 'barbell', 'forearms'),
('barbell palms up wrist curl over a bench', 'lower arms', 'barbell', 'forearms'),
('barbell pendlay row', 'back', 'barbell', 'upper back'),
('barbell pin presses', 'upper arms', 'barbell', 'triceps'),
('barbell preacher curl', 'upper arms', 'barbell', 'biceps'),
('barbell press sit-up', 'waist', 'barbell', 'abs'),
('barbell prone incline curl', 'upper arms', 'barbell', 'biceps'),
('barbell pullover', 'back', 'barbell', 'lats'),
('barbell pullover to press', 'back', 'barbell', 'lats'),
('barbell rack pull', 'upper legs', 'barbell', 'glutes'),
('barbell rear delt raise', 'shoulders', 'barbell', 'delts'),
('barbell rear delt row', 'shoulders', 'barbell', 'delts'),
('barbell rear lunge', 'upper legs', 'barbell', 'glutes'),
('barbell rear lunge v. 2', 'upper legs', 'barbell', 'glutes'),
('barbell revers wrist curl v. 2', 'lower arms', 'barbell', 'forearms'),
('barbell reverse close-grip bench press', 'upper arms', 'barbell', 'triceps'),
('barbell reverse curl', 'upper arms', 'barbell', 'biceps'),
('barbell reverse grip bent over row', 'back', 'barbell', 'upper back'),
('barbell reverse grip decline bench press', 'chest', 'barbell', 'pectorals'),
('barbell reverse grip incline bench press', 'chest', 'barbell', 'pectorals'),
('barbell reverse grip incline bench row', 'back', 'barbell', 'upper back'),
('barbell reverse grip skullcrusher', 'upper arms', 'barbell', 'triceps'),
('barbell reverse preacher curl', 'upper arms', 'barbell', 'biceps'),
('barbell reverse wrist curl', 'lower arms', 'barbell', 'forearms'),
('barbell rollerout', 'waist', 'barbell', 'abs'),
('barbell rollerout from bench', 'waist', 'barbell', 'abs'),
('barbell romanian deadlift', 'upper legs', 'barbell', 'glutes'),
('barbell seated behind head military press', 'shoulders', 'barbell', 'delts'),
('barbell seated bradford rocky press', 'shoulders', 'barbell', 'delts'),
('barbell seated calf raise', 'lower legs', 'barbell', 'calves'),
('barbell seated close grip behind neck triceps extension', 'upper arms', 'barbell', 'triceps'),
('barbell seated close-grip concentration curl', 'upper arms', 'barbell', 'biceps'),
('barbell seated good morning', 'upper legs', 'barbell', 'glutes'),
('barbell seated overhead press', 'shoulders', 'barbell', 'delts'),
('barbell seated overhead triceps extension', 'upper arms', 'barbell', 'triceps'),
('barbell seated twist', 'waist', 'barbell', 'abs'),
('barbell shrug', 'back', 'barbell', 'traps'),
('barbell side bent v. 2', 'waist', 'barbell', 'abs'),
('barbell side split squat', 'upper legs', 'barbell', 'quads'),
('barbell side split squat v. 2', 'upper legs', 'barbell', 'quads'),
('barbell single leg deadlift', 'upper legs', 'barbell', 'glutes'),
('barbell single leg split squat', 'upper legs', 'barbell', 'quads'),
('barbell sitted alternate leg raise', 'waist', 'barbell', 'abs'),
('barbell sitted alternate leg raise (female)', 'waist', 'barbell', 'abs')
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercises (name, body_part, equipment, target) VALUES
('barbell skier', 'shoulders', 'barbell', 'delts'),
('barbell speed squat', 'upper legs', 'barbell', 'glutes'),
('barbell split squat v. 2', 'upper legs', 'barbell', 'quads'),
('barbell squat (on knees)', 'upper legs', 'barbell', 'quads'),
('barbell squat jump step rear lunge', 'upper legs', 'barbell', 'quads'),
('barbell standing ab rollerout', 'waist', 'barbell', 'abs'),
('barbell standing back wrist curl', 'lower arms', 'barbell', 'forearms'),
('barbell standing bradford press', 'shoulders', 'barbell', 'delts'),
('barbell standing calf raise', 'lower legs', 'barbell', 'calves'),
('barbell standing close grip curl', 'upper arms', 'barbell', 'biceps'),
('barbell standing close grip military press', 'shoulders', 'barbell', 'delts'),
('barbell standing concentration curl', 'upper arms', 'barbell', 'biceps'),
('barbell standing front raise over head', 'shoulders', 'barbell', 'delts'),
('barbell standing leg calf raise', 'lower legs', 'barbell', 'calves'),
('barbell standing overhead triceps extension', 'upper arms', 'barbell', 'triceps'),
('barbell standing reverse grip curl', 'upper arms', 'barbell', 'biceps'),
('barbell standing rocking leg calf raise', 'lower legs', 'barbell', 'calves'),
('barbell standing twist', 'waist', 'barbell', 'abs'),
('barbell standing wide grip biceps curl', 'upper arms', 'barbell', 'biceps'),
('barbell standing wide military press', 'shoulders', 'barbell', 'delts'),
('barbell standing wide-grip curl', 'upper arms', 'barbell', 'biceps'),
('barbell step-up', 'upper legs', 'barbell', 'glutes'),
('barbell stiff leg good morning', 'upper legs', 'barbell', 'glutes'),
('barbell straight leg deadlift', 'upper legs', 'barbell', 'hamstrings'),
('barbell sumo deadlift', 'upper legs', 'barbell', 'glutes'),
('barbell thruster', 'shoulders', 'barbell', 'delts'),
('barbell upright row', 'shoulders', 'barbell', 'delts'),
('barbell upright row v. 2', 'shoulders', 'barbell', 'delts'),
('barbell upright row v. 3', 'shoulders', 'barbell', 'delts'),
('barbell wide bench press', 'chest', 'barbell', 'pectorals'),
('barbell wide reverse grip bench press', 'chest', 'barbell', 'pectorals'),
('barbell wide squat', 'upper legs', 'barbell', 'quads'),
('barbell wide-grip upright row', 'shoulders', 'barbell', 'delts'),
('barbell wrist curl', 'lower arms', 'barbell', 'forearms'),
('barbell wrist curl v. 2', 'lower arms', 'barbell', 'forearms'),
('barbell zercher squat', 'upper legs', 'barbell', 'glutes'),
('basic toe touch (male)', 'upper legs', 'body weight', 'glutes'),
('battling ropes', 'shoulders', 'rope', 'delts'),
('bear crawl', 'cardio', 'body weight', 'cardiovascular system'),
('behind head chest stretch', 'chest', 'assisted', 'pectorals'),
('bench dip (knees bent)', 'upper arms', 'body weight', 'triceps'),
('bench dip on floor', 'upper arms', 'body weight', 'triceps'),
('bench hip extension', 'upper legs', 'body weight', 'glutes'),
('bench pull-ups', 'back', 'body weight', 'lats'),
('bent knee lying twist (male)', 'upper legs', 'body weight', 'glutes'),
('biceps leg concentration curl', 'upper arms', 'body weight', 'biceps'),
('biceps narrow pull-ups', 'upper arms', 'body weight', 'biceps'),
('biceps pull-up', 'upper arms', 'body weight', 'biceps'),
('body-up', 'upper arms', 'body weight', 'triceps'),
('bodyweight drop jump squat', 'upper legs', 'body weight', 'glutes'),
('bodyweight incline side plank', 'waist', 'body weight', 'abs'),
('bodyweight kneeling triceps extension', 'upper arms', 'body weight', 'triceps'),
('bodyweight side lying biceps curl', 'upper arms', 'body weight', 'biceps'),
('bodyweight squatting row', 'back', 'body weight', 'upper back'),
('bodyweight squatting row (with towel)', 'back', 'body weight', 'upper back'),
('bodyweight standing calf raise', 'lower legs', 'body weight', 'calves'),
('bodyweight standing close-grip one arm row', 'back', 'body weight', 'upper back'),
('bodyweight standing close-grip row', 'back', 'body weight', 'upper back'),
('bodyweight standing one arm row', 'back', 'body weight', 'upper back'),
('bodyweight standing one arm row (with towel)', 'back', 'body weight', 'upper back'),
('bodyweight standing row', 'back', 'body weight', 'upper back'),
('bodyweight standing row (with towel)', 'back', 'body weight', 'upper back'),
('bottoms-up', 'waist', 'body weight', 'abs'),
('box jump down with one leg stabilization', 'lower legs', 'body weight', 'calves'),
('bridge - mountain climber (cross body)', 'waist', 'body weight', 'abs'),
('burpee', 'cardio', 'body weight', 'cardiovascular system'),
('butt-ups', 'waist', 'body weight', 'abs'),
('butterfly yoga pose', 'upper legs', 'body weight', 'adductors'),
('cable alternate shoulder press', 'shoulders', 'cable', 'delts'),
('cable alternate triceps extension', 'upper arms', 'cable', 'triceps'),
('cable assisted inverse leg curl', 'upper legs', 'cable', 'hamstrings'),
('cable bar lateral pulldown', 'back', 'cable', 'lats'),
('cable bench press', 'chest', 'cable', 'pectorals'),
('cable close grip curl', 'upper arms', 'cable', 'biceps'),
('cable concentration curl', 'upper arms', 'cable', 'biceps'),
('cable concentration extension (on knee)', 'upper arms', 'cable', 'triceps'),
('cable cross-over lateral pulldown', 'back', 'cable', 'lats'),
('cable cross-over revers fly', 'shoulders', 'cable', 'delts'),
('cable cross-over variation', 'chest', 'cable', 'pectorals'),
('cable curl', 'upper arms', 'cable', 'biceps'),
('cable deadlift', 'upper legs', 'cable', 'glutes'),
('cable decline fly', 'chest', 'cable', 'pectorals'),
('cable decline one arm press', 'chest', 'cable', 'pectorals'),
('cable decline press', 'chest', 'cable', 'pectorals'),
('cable decline seated wide-grip row', 'back', 'cable', 'upper back'),
('cable drag curl', 'upper arms', 'cable', 'biceps'),
('cable floor seated wide-grip row', 'back', 'cable', 'upper back'),
('cable forward raise', 'shoulders', 'cable', 'delts'),
('cable front raise', 'shoulders', 'cable', 'delts'),
('cable front shoulder raise', 'shoulders', 'cable', 'delts'),
('cable hammer curl (with rope)', 'upper arms', 'cable', 'biceps'),
('cable high pulley overhead tricep extension', 'upper arms', 'cable', 'triceps'),
('cable high row (kneeling)', 'back', 'cable', 'upper back'),
('cable hip adduction', 'upper legs', 'cable', 'adductors'),
('cable incline bench press', 'chest', 'cable', 'pectorals'),
('cable incline bench row', 'back', 'cable', 'upper back'),
('cable incline fly', 'chest', 'cable', 'pectorals'),
('cable incline fly (on stability ball)', 'chest', 'cable', 'pectorals'),
('cable incline pushdown', 'back', 'cable', 'lats'),
('cable incline triceps extension', 'upper arms', 'cable', 'triceps'),
('cable judo flip', 'waist', 'cable', 'abs'),
('cable kickback', 'upper arms', 'cable', 'triceps'),
('cable kneeling crunch', 'waist', 'cable', 'abs'),
('cable kneeling rear delt row (with rope) (male)', 'shoulders', 'cable', 'delts'),
('cable kneeling triceps extension', 'upper arms', 'cable', 'triceps'),
('cable lat pulldown full range of motion', 'back', 'cable', 'lats'),
('cable lateral pulldown (with rope attachment)', 'back', 'cable', 'lats'),
('cable lateral pulldown with v-bar', 'back', 'cable', 'lats'),
('cable lateral raise', 'shoulders', 'cable', 'delts'),
('cable low fly', 'chest', 'cable', 'pectorals'),
('cable low seated row', 'back', 'cable', 'upper back'),
('cable lying bicep curl', 'upper arms', 'cable', 'biceps'),
('cable lying close-grip curl', 'upper arms', 'cable', 'biceps'),
('cable lying extension pullover (with rope attachment)', 'back', 'cable', 'lats'),
('cable lying fly', 'chest', 'cable', 'pectorals'),
('cable lying triceps extension v. 2', 'upper arms', 'cable', 'triceps'),
('cable middle fly', 'chest', 'cable', 'pectorals'),
('cable one arm bent over row', 'back', 'cable', 'upper back'),
('cable one arm curl', 'upper arms', 'cable', 'biceps'),
('cable one arm decline chest fly', 'chest', 'cable', 'pectorals'),
('cable one arm fly on exercise ball', 'chest', 'cable', 'pectorals'),
('cable one arm incline fly on exercise ball', 'chest', 'cable', 'pectorals'),
('cable one arm incline press', 'chest', 'cable', 'pectorals'),
('cable one arm incline press on exercise ball', 'chest', 'cable', 'pectorals'),
('cable one arm lateral bent-over', 'chest', 'cable', 'pectorals'),
('cable one arm lateral raise', 'shoulders', 'cable', 'delts'),
('cable one arm preacher curl', 'upper arms', 'cable', 'biceps'),
('cable one arm press on exercise ball', 'chest', 'cable', 'pectorals'),
('cable one arm pulldown', 'back', 'cable', 'lats'),
('cable one arm reverse preacher curl', 'upper arms', 'cable', 'biceps'),
('cable one arm straight back high row (kneeling)', 'back', 'cable', 'upper back'),
('cable one arm tricep pushdown', 'upper arms', 'cable', 'triceps'),
('cable overhead curl', 'upper arms', 'cable', 'biceps'),
('cable overhead curl on exercise ball', 'upper arms', 'cable', 'biceps'),
('cable overhead triceps extension (rope attachment)', 'upper arms', 'cable', 'triceps'),
('cable palm rotational row', 'back', 'cable', 'upper back'),
('cable preacher curl', 'upper arms', 'cable', 'biceps'),
('cable press on exercise ball', 'chest', 'cable', 'pectorals'),
('cable pull through (with rope)', 'upper legs', 'cable', 'glutes'),
('cable pulldown', 'back', 'cable', 'lats'),
('cable pulldown (pro lat bar)', 'back', 'cable', 'lats'),
('cable pulldown bicep curl', 'upper arms', 'cable', 'biceps'),
('cable pushdown', 'upper arms', 'cable', 'triceps'),
('cable pushdown (straight arm) v. 2', 'back', 'cable', 'lats'),
('cable pushdown (with rope attachment)', 'upper arms', 'cable', 'triceps'),
('cable rear delt row (stirrups)', 'shoulders', 'cable', 'delts'),
('cable rear delt row (with rope)', 'shoulders', 'cable', 'delts'),
('cable rear drive', 'upper arms', 'cable', 'triceps'),
('cable rear pulldown', 'back', 'cable', 'lats'),
('cable reverse crunch', 'waist', 'cable', 'abs'),
('cable reverse curl', 'upper arms', 'cable', 'biceps'),
('cable reverse grip triceps pushdown (sz-bar) (with arm blaster)', 'upper arms', 'cable', 'triceps'),
('cable reverse one arm curl', 'upper arms', 'cable', 'biceps'),
('cable reverse preacher curl', 'upper arms', 'cable', 'biceps'),
('cable reverse wrist curl', 'lower arms', 'cable', 'forearms'),
('cable reverse-grip pushdown', 'upper arms', 'cable', 'triceps'),
('cable reverse-grip straight back seated high row', 'back', 'cable', 'upper back'),
('cable rope crossover seated row', 'back', 'cable', 'upper back'),
('cable rope elevated seated row', 'back', 'cable', 'upper back'),
('cable rope extension incline bench row', 'back', 'cable', 'upper back'),
('cable rope hammer preacher curl', 'upper arms', 'cable', 'biceps'),
('cable rope high pulley overhead tricep extension', 'upper arms', 'cable', 'triceps'),
('cable rope incline tricep extension', 'upper arms', 'cable', 'triceps'),
('cable rope lying on floor tricep extension', 'upper arms', 'cable', 'triceps'),
('cable rope one arm hammer preacher curl', 'upper arms', 'cable', 'biceps'),
('cable rope seated row', 'back', 'cable', 'upper back'),
('cable russian twists (on stability ball)', 'waist', 'cable', 'abs'),
('cable seated chest press', 'chest', 'cable', 'pectorals'),
('cable seated crunch', 'waist', 'cable', 'abs'),
('cable seated curl', 'upper arms', 'cable', 'biceps'),
('cable seated high row (v-bar)', 'back', 'cable', 'lats'),
('cable seated one arm alternate row', 'back', 'cable', 'upper back'),
('cable seated one arm concentration curl', 'upper arms', 'cable', 'biceps'),
('cable seated overhead curl', 'upper arms', 'cable', 'biceps'),
('cable seated rear lateral raise', 'shoulders', 'cable', 'delts'),
('cable seated row', 'back', 'cable', 'upper back'),
('cable seated shoulder internal rotation', 'shoulders', 'cable', 'delts'),
('cable seated twist', 'waist', 'cable', 'abs'),
('cable seated wide-grip row', 'back', 'cable', 'upper back'),
('cable shoulder press', 'shoulders', 'cable', 'delts'),
('cable shrug', 'back', 'cable', 'traps'),
('cable side bend', 'waist', 'cable', 'abs'),
('cable side bend crunch (bosu ball)', 'waist', 'cable', 'abs'),
('cable side crunch', 'waist', 'cable', 'abs'),
('cable squat row (with rope attachment)', 'back', 'cable', 'lats'),
('cable squatting curl', 'upper arms', 'cable', 'biceps'),
('cable standing back wrist curl', 'lower arms', 'cable', 'forearms'),
('cable standing calf raise', 'lower legs', 'cable', 'calves'),
('cable standing cross-over high reverse fly', 'shoulders', 'cable', 'delts'),
('cable standing crunch', 'waist', 'cable', 'abs'),
('cable standing crunch (with rope attachment)', 'waist', 'cable', 'abs'),
('cable standing fly', 'chest', 'cable', 'pectorals'),
('cable standing hip extension', 'upper legs', 'cable', 'glutes'),
('cable standing inner curl', 'upper arms', 'cable', 'biceps'),
('cable standing lift', 'waist', 'cable', 'abs'),
('cable standing one arm triceps extension', 'upper arms', 'cable', 'triceps'),
('cable standing one leg calf raise', 'lower legs', 'cable', 'calves'),
('cable standing pulldown (with rope)', 'upper arms', 'cable', 'biceps'),
('cable standing rear delt row (with rope)', 'shoulders', 'cable', 'delts'),
('cable standing reverse grip one arm overhead tricep extension', 'upper arms', 'cable', 'triceps')
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercises (name, body_part, equipment, target) VALUES
('cable standing row (v-bar)', 'back', 'cable', 'upper back'),
('cable standing shoulder external rotation', 'shoulders', 'cable', 'delts'),
('cable standing twist row (v-bar)', 'back', 'cable', 'upper back'),
('cable standing up straight crossovers', 'chest', 'cable', 'pectorals'),
('cable straight arm pulldown', 'back', 'cable', 'lats'),
('cable straight arm pulldown (with rope)', 'back', 'cable', 'lats'),
('cable straight back seated row', 'back', 'cable', 'upper back'),
('cable supine reverse fly', 'shoulders', 'cable', 'delts'),
('cable thibaudeau kayak row', 'back', 'cable', 'lats'),
('cable triceps pushdown (v-bar)', 'upper arms', 'cable', 'triceps'),
('cable triceps pushdown (v-bar) (with arm blaster)', 'upper arms', 'cable', 'triceps'),
('cable tuck reverse crunch', 'waist', 'cable', 'abs'),
('cable twist', 'waist', 'cable', 'abs'),
('cable twist (up-down)', 'waist', 'cable', 'abs'),
('cable twisting pull', 'back', 'cable', 'lats'),
('cable two arm curl on incline bench', 'upper arms', 'cable', 'biceps'),
('cable two arm tricep kickback', 'upper arms', 'cable', 'triceps'),
('cable underhand pulldown', 'back', 'cable', 'lats'),
('cable upper chest crossovers', 'chest', 'cable', 'pectorals'),
('cable upper row', 'back', 'cable', 'upper back'),
('cable upright row', 'shoulders', 'cable', 'delts'),
('cable wide grip rear pulldown behind neck', 'back', 'cable', 'lats'),
('cable wrist curl', 'lower arms', 'cable', 'forearms'),
('calf push stretch with hands against wall', 'lower legs', 'body weight', 'calves'),
('calf stretch with hands against wall', 'lower legs', 'body weight', 'calves'),
('calf stretch with rope', 'lower legs', 'rope', 'calves'),
('cambered bar lying row', 'back', 'barbell', 'upper back'),
('captains chair straight leg raise', 'waist', 'body weight', 'abs'),
('chair leg extended stretch', 'upper legs', 'body weight', 'quads'),
('chest and front of shoulder stretch', 'chest', 'body weight', 'pectorals'),
('chest dip', 'chest', 'body weight', 'pectorals'),
('chest dip (on dip-pull-up cage)', 'chest', 'body weight', 'pectorals'),
('chest dip on straight bar', 'chest', 'body weight', 'pectorals'),
('chest stretch with exercise ball', 'chest', 'stability ball', 'pectorals'),
('chest tap push-up (male)', 'chest', 'body weight', 'pectorals'),
('chin-up', 'back', 'body weight', 'lats'),
('chin-ups (narrow parallel grip)', 'back', 'body weight', 'upper back'),
('circles knee stretch', 'lower legs', 'body weight', 'calves'),
('clap push up', 'chest', 'body weight', 'pectorals'),
('clock push-up', 'chest', 'body weight', 'pectorals'),
('close grip chin-up', 'back', 'body weight', 'lats'),
('close-grip push-up', 'upper arms', 'body weight', 'triceps'),
('close-grip push-up (on knees)', 'upper arms', 'body weight', 'triceps'),
('cocoons', 'waist', 'body weight', 'abs'),
('crab twist toe touch', 'waist', 'body weight', 'abs'),
('cross body crunch', 'waist', 'body weight', 'abs'),
('crunch (hands overhead)', 'waist', 'body weight', 'abs'),
('crunch (on stability ball)', 'waist', 'stability ball', 'abs'),
('crunch (on stability ball, arms straight)', 'waist', 'stability ball', 'abs'),
('crunch floor', 'waist', 'body weight', 'abs'),
('curl-up', 'waist', 'body weight', 'abs'),
('curtsey squat', 'upper legs', 'body weight', 'glutes'),
('cycle cross trainer', 'cardio', 'leverage machine', 'cardiovascular system'),
('dead bug', 'waist', 'body weight', 'abs'),
('decline crunch', 'waist', 'body weight', 'abs'),
('decline push-up', 'chest', 'body weight', 'pectorals'),
('decline sit-up', 'waist', 'body weight', 'abs'),
('deep push up', 'chest', 'dumbbell', 'pectorals'),
('diamond push-up', 'upper arms', 'body weight', 'triceps'),
('donkey calf raise', 'lower legs', 'body weight', 'calves'),
('drop push up', 'chest', 'body weight', 'pectorals'),
('dumbbell alternate biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell alternate biceps curl (with arm blaster)', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell alternate hammer preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell alternate preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell alternate seated hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell alternate side press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell alternating bicep curl with leg raised on exercise ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell alternating seated bicep curl on exercise ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell arnold press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell arnold press v. 2', 'shoulders', 'dumbbell', 'delts'),
('dumbbell around pullover', 'chest', 'dumbbell', 'pectorals'),
('dumbbell bench press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell bench seated press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell bench squat', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell bent over row', 'back', 'dumbbell', 'upper back'),
('dumbbell bicep curl lunge with bowling motion', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell bicep curl on exercise ball with leg raised', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell bicep curl with stork stance', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell biceps curl (with arm blaster)', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell biceps curl reverse', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell biceps curl squat', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell biceps curl v sit on bosu ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell burpee', 'cardio', 'dumbbell', 'cardiovascular system'),
('dumbbell clean', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell close grip press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell close-grip press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell concentration curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell contralateral forward lunge', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell cross body hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell cross body hammer curl v. 2', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell cuban press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell cuban press v. 2', 'shoulders', 'dumbbell', 'delts'),
('dumbbell deadlift', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell decline bench press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell decline fly', 'chest', 'dumbbell', 'pectorals'),
('dumbbell decline hammer press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell decline one arm fly', 'chest', 'dumbbell', 'pectorals'),
('dumbbell decline one arm hammer press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell decline shrug', 'back', 'dumbbell', 'traps'),
('dumbbell decline shrug v. 2', 'back', 'dumbbell', 'traps'),
('dumbbell decline triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell decline twist fly', 'chest', 'dumbbell', 'pectorals'),
('dumbbell finger curls', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell fly', 'chest', 'dumbbell', 'pectorals'),
('dumbbell fly on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell forward lunge triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell front raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell front raise v. 2', 'shoulders', 'dumbbell', 'delts'),
('dumbbell full can lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell goblet squat', 'upper legs', 'dumbbell', 'quads'),
('dumbbell hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell hammer curl on exercise ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell hammer curl v. 2', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell hammer curls (with arm blaster)', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell high curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell incline alternate press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline bench press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell incline breeding', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell incline curl v. 2', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell incline fly', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline fly on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell incline hammer press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline hammer press on exercise ball', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell incline inner biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell incline one arm fly', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline one arm fly on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline one arm hammer press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell incline one arm hammer press on exercise ball', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell incline one arm lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell incline one arm press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline one arm press on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline palm-in press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline press on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell incline rear lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell incline row', 'back', 'dumbbell', 'upper back'),
('dumbbell incline shoulder raise', 'chest', 'dumbbell', 'serratus anterior'),
('dumbbell incline shrug', 'back', 'dumbbell', 'traps'),
('dumbbell incline t-raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell incline triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell incline twisted flyes', 'chest', 'dumbbell', 'pectorals'),
('dumbbell incline two arm extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell incline y-raise', 'back', 'dumbbell', 'upper back'),
('dumbbell iron cross', 'shoulders', 'dumbbell', 'delts'),
('dumbbell kickback', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell kickbacks on exercise ball', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell kneeling bicep curl exercise ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell lateral to front raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell lunge', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell lunge with bicep curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell lying extension (across face)', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell lying alternate extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell lying elbow press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell lying external shoulder rotation', 'shoulders', 'dumbbell', 'delts'),
('dumbbell lying femoral', 'upper legs', 'dumbbell', 'hamstrings'),
('dumbbell lying hammer press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell lying on floor rear delt raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell lying one arm deltoid rear', 'shoulders', 'dumbbell', 'delts'),
('dumbbell lying one arm press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell lying one arm press v. 2', 'chest', 'dumbbell', 'pectorals'),
('dumbbell lying one arm pronated triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell lying one arm rear lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell lying one arm supinated triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell lying pronation', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell lying pronation on floor', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell lying pullover on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell lying rear delt row', 'back', 'dumbbell', 'upper back'),
('dumbbell lying rear lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell lying single extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell lying supination', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell lying supination on floor', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell lying supine biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell lying supine curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell lying triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell lying wide curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell neutral grip bench press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell one arm bench fly', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm bent-over row', 'back', 'dumbbell', 'upper back'),
('dumbbell one arm chest fly on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm concentration curl (on stability ball)', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm decline chest press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm fly on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm french press on exercise ball', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell one arm hammer preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm hammer press on exercise ball', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell one arm incline chest press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm kickback', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell one arm lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell one arm lateral raise with support', 'shoulders', 'dumbbell', 'delts'),
('dumbbell one arm press on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm prone curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm prone hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm pullover on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm reverse wrist curl', 'lower arms', 'dumbbell', 'forearms')
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercises (name, body_part, equipment, target) VALUES
('dumbbell one arm reverse fly (with support)', 'shoulders', 'dumbbell', 'delts'),
('dumbbell one arm reverse grip press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell one arm reverse preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm reverse spider curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm seated bicep curl on exercise ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm seated hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm seated neutral wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell one arm shoulder press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell one arm shoulder press v. 2', 'shoulders', 'dumbbell', 'delts'),
('dumbbell one arm snatch', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell one arm standing curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm standing hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one arm triceps extension (on bench)', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell one arm upright row', 'shoulders', 'dumbbell', 'delts'),
('dumbbell one arm wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell one arm zottman preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell one leg fly on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell over bench neutral wrist curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell over bench one arm neutral wrist curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell over bench one arm reverse wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell over bench one arm wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell over bench revers wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell over bench wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell palm rotational bent over row', 'back', 'dumbbell', 'upper back'),
('dumbbell palms in incline bench press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell peacher hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell plyo squat', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell preacher curl over exercise ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell press on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell pronate-grip triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell prone incline curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell prone incline hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell pullover', 'chest', 'dumbbell', 'pectorals'),
('dumbbell pullover hip extension on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell pullover on exercise ball', 'chest', 'dumbbell', 'pectorals'),
('dumbbell push press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell rear delt raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell rear delt row_shoulder', 'shoulders', 'dumbbell', 'delts'),
('dumbbell rear fly', 'shoulders', 'dumbbell', 'delts'),
('dumbbell rear lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell rear lateral raise (support head)', 'shoulders', 'dumbbell', 'delts'),
('dumbbell rear lunge', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell revers grip biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell reverse bench press', 'chest', 'dumbbell', 'pectorals'),
('dumbbell reverse fly', 'shoulders', 'dumbbell', 'delts'),
('dumbbell reverse grip incline bench one arm row', 'back', 'dumbbell', 'upper back'),
('dumbbell reverse grip incline bench two arm row', 'back', 'dumbbell', 'upper back'),
('dumbbell reverse grip row (female)', 'back', 'dumbbell', 'upper back'),
('dumbbell reverse preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell reverse spider curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell reverse wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell romanian deadlift', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell rotation reverse fly', 'shoulders', 'dumbbell', 'delts'),
('dumbbell scott press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated alternate front raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated alternate hammer curl on exercise ball', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated alternate press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated alternate shoulder', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated bench extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell seated bent arm lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated bent over alternate kickback', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell seated bent over triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell seated bicep curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated biceps curl (on stability ball)', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated biceps curl to shoulder press', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated calf raise', 'lower legs', 'dumbbell', 'calves'),
('dumbbell seated curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated front raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated hammer curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated inner biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated kickback', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell seated lateral raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated lateral raise v. 2', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated neutral wrist curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated one arm bicep curl on exercise ball with leg raised', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated one arm kickback', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell seated one arm rotate', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell seated one leg calf raise', 'lower legs', 'dumbbell', 'calves'),
('dumbbell seated one leg calf raise - hammer grip', 'lower legs', 'dumbbell', 'calves'),
('dumbbell seated one leg calf raise - palm up', 'lower legs', 'dumbbell', 'calves'),
('dumbbell seated palms up wrist curl', 'lower arms', 'dumbbell', 'forearms'),
('dumbbell seated preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated revers grip concentration curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell seated reverse grip one arm overhead tricep extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell seated shoulder press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated shoulder press (parallel grip)', 'shoulders', 'dumbbell', 'delts'),
('dumbbell seated triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell shrug', 'back', 'dumbbell', 'traps'),
('dumbbell side bend', 'waist', 'dumbbell', 'abs'),
('dumbbell side lying one hand raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell side plank with rear fly', 'back', 'dumbbell', 'upper back'),
('dumbbell single arm overhead carry', 'shoulders', 'dumbbell', 'delts'),
('dumbbell single leg calf raise', 'lower legs', 'dumbbell', 'calves'),
('dumbbell single leg deadlift', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell single leg deadlift with stepbox support', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell single leg split squat', 'upper legs', 'dumbbell', 'quads'),
('dumbbell single leg squat', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell squat', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell standing alternate hammer curl and press', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing alternate overhead press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell standing alternate raise', 'shoulders', 'dumbbell', 'delts'),
('dumbbell standing alternating tricep kickback', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell standing around world', 'shoulders', 'dumbbell', 'delts'),
('dumbbell standing bent over one arm triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell standing bent over two arm triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell standing biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing calf raise', 'lower legs', 'dumbbell', 'calves'),
('dumbbell standing concentration curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing front raise above head', 'shoulders', 'dumbbell', 'delts'),
('dumbbell standing inner biceps curl v. 2', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing kickback', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell standing one arm concentration curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing one arm curl (over incline bench)', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing one arm curl over incline bench', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing one arm extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell standing one arm palm in press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell standing one arm reverse curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing overhead press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell standing palms in press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell standing preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing reverse curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell standing triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell standing zottman preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell step up single leg balance with bicep curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell step-up', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell step-up lunge', 'upper legs', 'dumbbell', 'quads'),
('dumbbell step-up split squat', 'upper legs', 'dumbbell', 'quads'),
('dumbbell stiff leg deadlift', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell straight arm pullover', 'chest', 'dumbbell', 'pectorals'),
('dumbbell straight leg deadlift', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell sumo pull through', 'upper legs', 'dumbbell', 'glutes'),
('dumbbell supported squat', 'upper legs', 'dumbbell', 'quads'),
('dumbbell tate press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell tricep kickback with stork stance', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell twisting bench press', 'upper arms', 'dumbbell', 'triceps'),
('dumbbell upright row', 'shoulders', 'dumbbell', 'delts'),
('dumbbell upright row (back pov)', 'shoulders', 'dumbbell', 'delts'),
('dumbbell upright shoulder external rotation', 'shoulders', 'dumbbell', 'delts'),
('dumbbell waiter biceps curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell w-press', 'shoulders', 'dumbbell', 'delts'),
('dumbbell zottman curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbell zottman preacher curl', 'upper arms', 'dumbbell', 'biceps'),
('dumbbells seated triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('dynamic chest stretch (male)', 'chest', 'body weight', 'pectorals'),
('elbow dips', 'upper arms', 'body weight', 'triceps'),
('elbow lift - reverse push-up', 'back', 'body weight', 'upper back'),
('elbow-to-knee', 'waist', 'body weight', 'abs'),
('elevator', 'back', 'body weight', 'upper back'),
('exercise ball alternating arm ups', 'back', 'stability ball', 'lats'),
('exercise ball back extension with arms extended', 'back', 'stability ball', 'spine'),
('exercise ball back extension with hands behind head', 'back', 'stability ball', 'spine'),
('exercise ball back extension with knees off ground', 'back', 'stability ball', 'spine'),
('exercise ball back extension with rotation', 'back', 'stability ball', 'spine'),
('exercise ball dip', 'upper arms', 'stability ball', 'triceps'),
('exercise ball hip flexor stretch', 'upper legs', 'stability ball', 'glutes'),
('exercise ball hug', 'back', 'stability ball', 'spine'),
('exercise ball lat stretch', 'back', 'stability ball', 'lats'),
('exercise ball lower back stretch (pyramid)', 'back', 'stability ball', 'lats'),
('exercise ball lying side lat stretch', 'back', 'stability ball', 'lats'),
('exercise ball on the wall calf raise', 'lower legs', 'dumbbell', 'calves'),
('exercise ball on the wall calf raise (tennis ball between ankles)', 'lower legs', 'dumbbell', 'calves'),
('exercise ball on the wall calf raise (tennis ball between knees)', 'lower legs', 'dumbbell', 'calves'),
('exercise ball one leg prone lower body rotation', 'upper legs', 'stability ball', 'glutes'),
('exercise ball one legged diagonal kick hamstring curl', 'upper legs', 'stability ball', 'glutes'),
('exercise ball pike push up', 'chest', 'stability ball', 'pectorals'),
('exercise ball prone leg raise', 'back', 'stability ball', 'spine'),
('exercise ball seated hamstring stretch', 'upper legs', 'stability ball', 'hamstrings'),
('exercise ball seated triceps stretch', 'upper arms', 'stability ball', 'triceps'),
('exercise ball supine triceps extension', 'upper arms', 'dumbbell', 'triceps'),
('ez bar french press on exercise ball', 'upper arms', 'ez barbell', 'triceps'),
('ez bar lying bent arms pullover', 'back', 'ez barbell', 'lats'),
('ez bar lying close grip triceps extension behind head', 'upper arms', 'ez barbell', 'triceps'),
('ez bar reverse grip bent over row', 'back', 'ez barbell', 'upper back'),
('ez bar seated close grip concentration curl', 'upper arms', 'ez barbell', 'biceps'),
('ez bar standing french press', 'upper arms', 'ez barbell', 'triceps'),
('ez barbell anti gravity press', 'shoulders', 'ez barbell', 'delts'),
('ez barbell close grip preacher curl', 'upper arms', 'ez barbell', 'biceps'),
('ez barbell close-grip curl', 'upper arms', 'ez barbell', 'biceps'),
('ez barbell curl', 'upper arms', 'ez barbell', 'biceps'),
('ez barbell decline close grip face press', 'upper arms', 'ez barbell', 'triceps'),
('ez barbell decline triceps extension', 'upper arms', 'ez barbell', 'triceps'),
('ez barbell incline triceps extension', 'upper arms', 'ez barbell', 'triceps'),
('ez barbell jm bench press', 'upper arms', 'ez barbell', 'triceps'),
('ez barbell reverse grip curl', 'upper arms', 'ez barbell', 'biceps'),
('ez barbell reverse grip preacher curl', 'upper arms', 'ez barbell', 'biceps'),
('ez barbell seated curls', 'upper arms', 'ez barbell', 'biceps'),
('ez barbell seated triceps extension', 'upper arms', 'ez barbell', 'triceps'),
('ez barbell spider curl', 'upper arms', 'ez barbell', 'biceps'),
('ez-bar biceps curl (with arm blaster)', 'upper arms', 'ez barbell', 'biceps'),
('ez-bar close-grip bench press', 'upper arms', 'ez barbell', 'triceps'),
('ez-barbell standing wide grip biceps curl', 'upper arms', 'ez barbell', 'biceps'),
('farmers walk', 'upper legs', 'dumbbell', 'quads'),
('finger curls', 'lower arms', 'barbell', 'forearms'),
('flag', 'waist', 'body weight', 'abs'),
('flexion leg sit up (bent knee)', 'waist', 'body weight', 'abs'),
('flexion leg sit up (straight arm)', 'waist', 'body weight', 'abs'),
('floor fly (with barbell)', 'chest', 'barbell', 'pectorals'),
('flutter kicks', 'upper legs', 'body weight', 'glutes')
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercises (name, body_part, equipment, target) VALUES
('forward jump', 'upper legs', 'body weight', 'quads'),
('forward lunge (male)', 'upper legs', 'body weight', 'glutes'),
('frankenstein squat', 'upper legs', 'barbell', 'glutes'),
('frog crunch', 'waist', 'body weight', 'abs'),
('frog planche', 'waist', 'body weight', 'abs'),
('front lever', 'waist', 'body weight', 'abs'),
('front lever reps', 'back', 'body weight', 'upper back'),
('front plank with twist', 'waist', 'body weight', 'abs'),
('full maltese', 'waist', 'body weight', 'abs'),
('full planche', 'waist', 'body weight', 'abs'),
('full planche push-up', 'chest', 'body weight', 'pectorals'),
('gironda sternum chin', 'back', 'body weight', 'lats'),
('glute bridge march', 'upper legs', 'body weight', 'glutes'),
('glute bridge two legs on bench (male)', 'upper legs', 'body weight', 'glutes'),
('glute-ham raise', 'upper legs', 'body weight', 'hamstrings'),
('gorilla chin', 'waist', 'body weight', 'abs'),
('groin crunch', 'waist', 'body weight', 'abs'),
('hack calf raise', 'lower legs', 'sled machine', 'calves'),
('hack one leg calf raise', 'lower legs', 'sled machine', 'calves'),
('half knee bends (male)', 'cardio', 'body weight', 'cardiovascular system'),
('half sit-up (male)', 'waist', 'body weight', 'abs'),
('hamstring stretch', 'upper legs', 'body weight', 'hamstrings'),
('hands bike', 'chest', 'upper body ergometer', 'pectorals'),
('hands clasped circular toe touch (male)', 'upper legs', 'body weight', 'glutes'),
('hands reversed clasped circular toe touch (male)', 'upper legs', 'body weight', 'glutes'),
('handstand', 'upper arms', 'body weight', 'triceps'),
('handstand push-up', 'upper arms', 'body weight', 'triceps'),
('hanging leg hip raise', 'waist', 'body weight', 'abs'),
('hanging leg raise', 'waist', 'body weight', 'abs'),
('hanging oblique knee raise', 'waist', 'body weight', 'abs'),
('hanging pike', 'waist', 'body weight', 'abs'),
('hanging straight leg hip raise', 'waist', 'body weight', 'abs'),
('hanging straight leg raise', 'waist', 'body weight', 'abs'),
('hanging straight twisting leg hip raise', 'waist', 'body weight', 'abs'),
('high knee against wall', 'cardio', 'body weight', 'cardiovascular system'),
('hip raise (bent knee)', 'waist', 'body weight', 'abs'),
('hug keens to chest', 'upper legs', 'body weight', 'glutes'),
('hyght dumbbell fly', 'chest', 'dumbbell', 'pectorals'),
('hyperextension', 'back', 'body weight', 'spine'),
('hyperextension (on bench)', 'back', 'body weight', 'spine'),
('impossible dips', 'upper arms', 'body weight', 'triceps'),
('inchworm', 'waist', 'body weight', 'abs'),
('inchworm v. 2', 'waist', 'body weight', 'abs'),
('incline close-grip push-up', 'upper arms', 'body weight', 'triceps'),
('incline leg hip raise (leg straight)', 'waist', 'body weight', 'abs'),
('incline push up depth jump', 'chest', 'body weight', 'pectorals'),
('incline push-up', 'chest', 'body weight', 'pectorals'),
('incline push-up (on box)', 'chest', 'body weight', 'pectorals'),
('incline reverse grip push-up', 'chest', 'body weight', 'pectorals'),
('incline scapula push up', 'chest', 'body weight', 'serratus anterior'),
('incline twisting sit-up', 'waist', 'body weight', 'abs'),
('intermediate hip flexor and quad stretch', 'upper legs', 'rope', 'quads'),
('inverse leg curl (bench support)', 'upper legs', 'body weight', 'hamstrings'),
('inverse leg curl (on pull-up cable machine)', 'upper legs', 'body weight', 'hamstrings'),
('inverted row', 'back', 'body weight', 'upper back'),
('inverted row bent knees', 'back', 'body weight', 'upper back'),
('inverted row on bench', 'back', 'body weight', 'upper back'),
('inverted row v. 2', 'back', 'body weight', 'upper back'),
('inverted row with straps', 'back', 'body weight', 'upper back'),
('iron cross stretch', 'upper legs', 'body weight', 'glutes'),
('isometric chest squeeze', 'chest', 'body weight', 'pectorals'),
('isometric wipers', 'chest', 'body weight', 'pectorals'),
('jack burpee', 'cardio', 'body weight', 'cardiovascular system'),
('jack jump (male)', 'cardio', 'body weight', 'cardiovascular system'),
('jackknife sit-up', 'waist', 'body weight', 'abs'),
('janda sit-up', 'waist', 'body weight', 'abs'),
('jump rope', 'cardio', 'rope', 'cardiovascular system'),
('jump squat', 'upper legs', 'body weight', 'glutes'),
('jump squat v. 2', 'upper legs', 'body weight', 'glutes'),
('kettlebell advanced windmill', 'waist', 'kettlebell', 'abs'),
('kettlebell alternating hang clean', 'lower arms', 'kettlebell', 'forearms'),
('kettlebell alternating press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell alternating press on floor', 'chest', 'kettlebell', 'pectorals'),
('kettlebell alternating renegade row', 'back', 'kettlebell', 'upper back'),
('kettlebell alternating row', 'back', 'kettlebell', 'upper back'),
('kettlebell arnold press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell bent press', 'waist', 'kettlebell', 'abs'),
('kettlebell bottoms up clean from the hang position', 'upper arms', 'kettlebell', 'biceps'),
('kettlebell double alternating hang clean', 'upper arms', 'kettlebell', 'biceps'),
('kettlebell double jerk', 'shoulders', 'kettlebell', 'delts'),
('kettlebell double push press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell double snatch', 'shoulders', 'kettlebell', 'delts'),
('kettlebell double windmill', 'waist', 'kettlebell', 'abs'),
('kettlebell extended range one arm press on floor', 'chest', 'kettlebell', 'pectorals'),
('kettlebell figure 8', 'waist', 'kettlebell', 'abs'),
('kettlebell front squat', 'upper legs', 'kettlebell', 'glutes'),
('kettlebell goblet squat', 'upper legs', 'kettlebell', 'glutes'),
('kettlebell hang clean', 'upper legs', 'kettlebell', 'hamstrings'),
('kettlebell lunge pass through', 'upper legs', 'kettlebell', 'glutes'),
('kettlebell one arm clean and jerk', 'shoulders', 'kettlebell', 'delts'),
('kettlebell one arm floor press', 'chest', 'kettlebell', 'pectorals'),
('kettlebell one arm jerk', 'shoulders', 'kettlebell', 'delts'),
('kettlebell one arm military press to the side', 'shoulders', 'kettlebell', 'delts'),
('kettlebell one arm push press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell one arm row', 'back', 'kettlebell', 'upper back'),
('kettlebell one arm snatch', 'shoulders', 'kettlebell', 'delts'),
('kettlebell pirate supper legs', 'shoulders', 'kettlebell', 'delts'),
('kettlebell pistol squat', 'upper legs', 'kettlebell', 'glutes'),
('kettlebell plyo push-up', 'chest', 'kettlebell', 'pectorals'),
('kettlebell seated press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell seated two arm military press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell seesaw press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell sumo high pull', 'back', 'kettlebell', 'traps'),
('kettlebell swing', 'upper legs', 'kettlebell', 'glutes'),
('kettlebell thruster', 'shoulders', 'kettlebell', 'delts'),
('kettlebell turkish get up (squat style)', 'upper legs', 'kettlebell', 'glutes'),
('kettlebell two arm clean', 'shoulders', 'kettlebell', 'delts'),
('kettlebell two arm military press', 'shoulders', 'kettlebell', 'delts'),
('kettlebell two arm row', 'back', 'kettlebell', 'upper back'),
('kettlebell windmill', 'waist', 'kettlebell', 'abs'),
('kick out sit', 'upper legs', 'body weight', 'hamstrings'),
('kipping muscle up', 'back', 'body weight', 'lats'),
('knee touch crunch', 'waist', 'body weight', 'abs'),
('kneeling jump squat', 'upper legs', 'barbell', 'glutes'),
('kneeling lat stretch', 'back', 'body weight', 'lats'),
('kneeling plank tap shoulder (male)', 'waist', 'body weight', 'abs'),
('kneeling push-up (male)', 'chest', 'body weight', 'pectorals'),
('korean dips', 'chest', 'body weight', 'pectorals'),
('l-pull-up', 'back', 'body weight', 'lats'),
('l-sit on floor', 'waist', 'body weight', 'abs'),
('landmine 180', 'waist', 'barbell', 'abs'),
('landmine lateral raise', 'shoulders', 'barbell', 'delts'),
('lean planche', 'waist', 'body weight', 'abs'),
('left hook. boxing', 'shoulders', 'body weight', 'delts'),
('leg pull in flat bench', 'waist', 'body weight', 'abs'),
('leg up hamstring stretch', 'upper legs', 'body weight', 'hamstrings'),
('lever alternate leg press', 'upper legs', 'leverage machine', 'quads'),
('lever alternating narrow grip seated row', 'back', 'leverage machine', 'upper back'),
('lever assisted chin-up', 'back', 'leverage machine', 'lats'),
('lever back extension', 'back', 'leverage machine', 'spine'),
('lever bent over row', 'back', 'barbell', 'upper back'),
('lever bent-over row with v-bar', 'back', 'leverage machine', 'upper back'),
('lever bicep curl', 'upper arms', 'leverage machine', 'biceps'),
('lever calf press', 'lower legs', 'leverage machine', 'calves'),
('lever chest press', 'chest', 'leverage machine', 'pectorals'),
('lever deadlift', 'upper legs', 'leverage machine', 'glutes'),
('lever decline chest press', 'chest', 'leverage machine', 'pectorals'),
('lever donkey calf raise', 'lower legs', 'leverage machine', 'calves'),
('lever front pulldown', 'back', 'leverage machine', 'lats'),
('lever gripless shrug', 'back', 'leverage machine', 'traps'),
('lever gripless shrug v. 2', 'back', 'leverage machine', 'traps'),
('lever gripper hands', 'lower arms', 'leverage machine', 'forearms'),
('lever hammer grip preacher curl', 'upper arms', 'leverage machine', 'biceps'),
('lever high row', 'back', 'leverage machine', 'upper back'),
('lever hip extension v. 2', 'upper legs', 'leverage machine', 'glutes'),
('lever horizontal one leg press', 'upper legs', 'leverage machine', 'glutes'),
('lever incline chest press', 'chest', 'leverage machine', 'pectorals'),
('lever incline chest press v. 2', 'chest', 'leverage machine', 'pectorals'),
('lever kneeling leg curl', 'upper legs', 'leverage machine', 'hamstrings'),
('lever kneeling twist', 'waist', 'leverage machine', 'abs'),
('lever lateral raise', 'shoulders', 'leverage machine', 'delts'),
('lever leg extension', 'upper legs', 'leverage machine', 'quads'),
('lever lying leg curl', 'upper legs', 'leverage machine', 'hamstrings'),
('lever lying two-one leg curl', 'upper legs', 'leverage machine', 'hamstrings'),
('lever military press', 'shoulders', 'leverage machine', 'delts'),
('lever narrow grip seated row', 'back', 'leverage machine', 'upper back'),
('lever one arm bent over row', 'back', 'barbell', 'upper back'),
('lever one arm lateral high row', 'back', 'leverage machine', 'upper back'),
('lever one arm lateral wide pulldown', 'back', 'leverage machine', 'lats'),
('lever one arm shoulder press', 'shoulders', 'leverage machine', 'delts'),
('lever overhand triceps dip', 'upper arms', 'leverage machine', 'triceps'),
('lever preacher curl', 'upper arms', 'leverage machine', 'biceps'),
('lever preacher curl v. 2', 'upper arms', 'leverage machine', 'biceps'),
('lever pullover', 'back', 'leverage machine', 'lats'),
('lever reverse grip lateral pulldown', 'back', 'leverage machine', 'lats'),
('lever reverse grip preacher curl', 'upper arms', 'leverage machine', 'biceps'),
('lever reverse grip vertical row', 'back', 'leverage machine', 'upper back'),
('lever reverse hyperextension', 'upper legs', 'leverage machine', 'glutes'),
('lever reverse t-bar row', 'back', 'leverage machine', 'upper back'),
('lever rotary calf', 'lower legs', 'leverage machine', 'calves'),
('lever seated calf press', 'lower legs', 'leverage machine', 'calves'),
('lever seated calf raise', 'lower legs', 'leverage machine', 'calves'),
('lever seated crunch', 'waist', 'leverage machine', 'abs'),
('lever seated crunch (chest pad)', 'waist', 'leverage machine', 'abs'),
('lever seated crunch v. 2', 'waist', 'leverage machine', 'abs'),
('lever seated dip', 'upper arms', 'leverage machine', 'triceps'),
('lever seated fly', 'chest', 'leverage machine', 'pectorals'),
('lever seated good morning', 'upper legs', 'leverage machine', 'glutes'),
('lever seated hip abduction', 'upper legs', 'leverage machine', 'abductors'),
('lever seated hip adduction', 'upper legs', 'leverage machine', 'adductors'),
('lever seated leg curl', 'upper legs', 'leverage machine', 'hamstrings'),
('lever seated leg raise crunch', 'waist', 'leverage machine', 'abs'),
('lever seated reverse fly', 'shoulders', 'leverage machine', 'delts'),
('lever seated reverse fly (parallel grip)', 'shoulders', 'leverage machine', 'delts'),
('lever seated row', 'back', 'leverage machine', 'upper back'),
('lever seated squat calf raise on leg press machine', 'lower legs', 'leverage machine', 'calves'),
('lever shoulder press', 'shoulders', 'leverage machine', 'delts'),
('lever shoulder press v. 2', 'shoulders', 'leverage machine', 'delts'),
('lever shoulder press v. 3', 'shoulders', 'leverage machine', 'delts'),
('lever shrug', 'back', 'leverage machine', 'traps'),
('lever standing calf raise', 'lower legs', 'leverage machine', 'calves'),
('lever standing chest press', 'chest', 'leverage machine', 'pectorals'),
('lever t bar row', 'back', 'leverage machine', 'upper back'),
('lever t-bar reverse grip row', 'back', 'leverage machine', 'upper back'),
('lever triceps extension', 'upper arms', 'leverage machine', 'triceps'),
('lever unilateral row', 'back', 'leverage machine', 'upper back'),
('london bridge', 'back', 'rope', 'upper back'),
('low glute bridge on floor', 'upper legs', 'body weight', 'glutes'),
('lower back curl', 'back', 'body weight', 'spine'),
('lunge with jump', 'upper legs', 'body weight', 'glutes')
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercises (name, body_part, equipment, target) VALUES
('lunge with twist', 'waist', 'body weight', 'abs'),
('lying (side) quads stretch', 'upper legs', 'body weight', 'quads'),
('lying elbow to knee', 'waist', 'body weight', 'abs'),
('lying leg raise flat bench', 'waist', 'body weight', 'abs'),
('lying leg-hip raise', 'waist', 'body weight', 'abs'),
('machine inner chest press', 'chest', 'leverage machine', 'pectorals'),
('march sit (wall)', 'upper legs', 'body weight', 'glutes'),
('medicine ball catch and overhead throw', 'back', 'medicine ball', 'lats'),
('medicine ball chest pass', 'chest', 'medicine ball', 'pectorals'),
('medicine ball chest push from 3 point stance', 'chest', 'medicine ball', 'pectorals'),
('medicine ball chest push multiple response', 'chest', 'medicine ball', 'pectorals'),
('medicine ball chest push single response', 'chest', 'medicine ball', 'pectorals'),
('medicine ball chest push with run release', 'chest', 'medicine ball', 'pectorals'),
('medicine ball close grip push up', 'upper arms', 'medicine ball', 'triceps'),
('medicine ball overhead slam', 'back', 'medicine ball', 'upper back'),
('medicine ball supine chest throw', 'upper arms', 'medicine ball', 'triceps'),
('mixed grip chin-up', 'back', 'body weight', 'lats'),
('modified hindu push-up (male)', 'chest', 'body weight', 'pectorals'),
('modified push up to lower arms', 'lower arms', 'body weight', 'forearms'),
('monster walk', 'upper legs', 'body weight', 'glutes'),
('mountain climber', 'cardio', 'body weight', 'cardiovascular system'),
('muscle up', 'back', 'body weight', 'lats'),
('muscle-up (on vertical bar)', 'back', 'body weight', 'lats'),
('narrow push-up on exercise ball', 'upper arms', 'stability ball', 'triceps'),
('neck side stretch', 'neck', 'body weight', 'levator scapulae'),
('negative crunch', 'waist', 'body weight', 'abs'),
('oblique crunch v. 2', 'waist', 'body weight', 'abs'),
('oblique crunches floor', 'waist', 'body weight', 'abs'),
('olympic barbell hammer curl', 'upper arms', 'olympic barbell', 'biceps'),
('olympic barbell triceps extension', 'upper arms', 'olympic barbell', 'triceps'),
('one arm against wall', 'back', 'body weight', 'lats'),
('one arm chin-up', 'back', 'body weight', 'lats'),
('one arm dip', 'upper arms', 'body weight', 'triceps'),
('one arm slam (with medicine ball)', 'waist', 'medicine ball', 'abs'),
('one arm towel row', 'back', 'body weight', 'upper back'),
('one leg donkey calf raise', 'lower legs', 'body weight', 'calves'),
('one leg floor calf raise', 'lower legs', 'body weight', 'calves'),
('one leg squat', 'upper legs', 'body weight', 'glutes'),
('otis up', 'waist', 'weighted', 'abs'),
('outside leg kick push-up', 'upper legs', 'body weight', 'glutes'),
('overhead triceps stretch', 'upper arms', 'body weight', 'triceps'),
('pelvic tilt', 'waist', 'body weight', 'abs'),
('pelvic tilt into bridge', 'upper legs', 'body weight', 'glutes'),
('peroneals stretch', 'lower legs', 'rope', 'calves'),
('pike-to-cobra push-up', 'upper legs', 'body weight', 'glutes'),
('plyo push up', 'chest', 'body weight', 'pectorals'),
('posterior step to overhead reach', 'waist', 'body weight', 'abs'),
('posterior tibialis stretch', 'lower legs', 'rope', 'calves'),
('potty squat', 'waist', 'body weight', 'abs'),
('potty squat with support', 'upper legs', 'body weight', 'glutes'),
('power clean', 'upper legs', 'barbell', 'hamstrings'),
('power point plank', 'waist', 'body weight', 'abs'),
('prisoner half sit-up (male)', 'waist', 'body weight', 'abs'),
('prone twist on stability ball', 'waist', 'stability ball', 'abs'),
('pull up (neutral grip)', 'back', 'body weight', 'lats'),
('pull-in (on stability ball)', 'waist', 'stability ball', 'abs'),
('pull-up', 'back', 'body weight', 'lats'),
('push and pull bodyweight', 'chest', 'body weight', 'pectorals'),
('push to run', 'cardio', 'body weight', 'cardiovascular system'),
('push up on bosu ball', 'chest', 'bosu ball', 'pectorals'),
('push-up', 'chest', 'body weight', 'pectorals'),
('push-up (bosu ball)', 'chest', 'bosu ball', 'pectorals'),
('push-up (on stability ball)', 'chest', 'stability ball', 'pectorals'),
('push-up (wall)', 'chest', 'body weight', 'pectorals'),
('push-up (wall) v. 2', 'chest', 'body weight', 'pectorals'),
('push-up close-grip off dumbbell', 'upper arms', 'dumbbell', 'triceps'),
('push-up inside leg kick', 'upper legs', 'body weight', 'glutes'),
('push-up medicine ball', 'chest', 'medicine ball', 'pectorals'),
('push-up on lower arms', 'upper arms', 'body weight', 'triceps'),
('push-up plus', 'chest', 'body weight', 'pectorals'),
('push-up to side plank', 'waist', 'body weight', 'abs'),
('quads', 'upper legs', 'body weight', 'quads'),
('quarter sit-up', 'waist', 'body weight', 'abs'),
('quick feet v. 2', 'upper legs', 'body weight', 'quads'),
('raise single arm push-up', 'chest', 'body weight', 'pectorals'),
('rear decline bridge', 'upper legs', 'body weight', 'glutes'),
('rear deltoid stretch', 'shoulders', 'body weight', 'delts'),
('rear pull-up', 'back', 'body weight', 'lats'),
('reclining big toe pose with rope', 'upper legs', 'rope', 'hamstrings'),
('resistance band hip thrusts on knees (female)', 'upper legs', 'resistance band', 'glutes'),
('resistance band leg extension', 'upper legs', 'resistance band', 'quads'),
('resistance band seated biceps curl', 'upper arms', 'resistance band', 'biceps'),
('resistance band seated chest press', 'chest', 'resistance band', 'pectorals'),
('resistance band seated hip abduction', 'upper legs', 'resistance band', 'abductors'),
('resistance band seated shoulder press', 'shoulders', 'resistance band', 'delts'),
('resistance band seated straight back row', 'back', 'resistance band', 'upper back'),
('reverse crunch', 'waist', 'body weight', 'abs'),
('reverse dip', 'upper arms', 'body weight', 'triceps'),
('reverse grip machine lat pulldown', 'back', 'leverage machine', 'lats'),
('reverse grip pull-up', 'back', 'body weight', 'lats'),
('reverse hyper extension (on stability ball)', 'upper legs', 'stability ball', 'glutes'),
('reverse hyper on flat bench', 'upper legs', 'body weight', 'glutes'),
('reverse plank with leg lift', 'waist', 'body weight', 'abs'),
('ring dips', 'upper arms', 'body weight', 'triceps'),
('rocking frog stretch', 'upper legs', 'body weight', 'glutes'),
('rocky pull-up pulldown', 'back', 'body weight', 'lats'),
('roller back stretch', 'back', 'roller', 'spine'),
('roller body saw', 'waist', 'roller', 'abs'),
('roller hip lat stretch', 'upper legs', 'roller', 'glutes'),
('roller hip stretch', 'upper legs', 'roller', 'glutes'),
('roller reverse crunch', 'waist', 'roller', 'abs'),
('roller seated shoulder flexor depresor retractor', 'chest', 'roller', 'pectorals'),
('roller seated single leg shoulder flexor depresor retractor', 'chest', 'roller', 'pectorals'),
('roller side lat stretch', 'back', 'roller', 'lats'),
('rope climb', 'back', 'rope', 'upper back'),
('run', 'cardio', 'body weight', 'cardiovascular system'),
('run (equipment)', 'cardio', 'body weight', 'cardiovascular system'),
('runners stretch', 'upper legs', 'body weight', 'hamstrings'),
('russian twist', 'waist', 'body weight', 'abs'),
('scapula dips', 'back', 'body weight', 'traps'),
('scapula push-up', 'chest', 'body weight', 'serratus anterior'),
('scapular pull-up', 'back', 'body weight', 'traps'),
('scissor jumps (male)', 'cardio', 'body weight', 'cardiovascular system'),
('seated calf stretch (male)', 'lower legs', 'body weight', 'calves'),
('seated glute stretch', 'upper legs', 'body weight', 'glutes'),
('seated leg raise', 'waist', 'body weight', 'abs'),
('seated lower back stretch', 'back', 'body weight', 'lats'),
('seated piriformis stretch', 'upper legs', 'body weight', 'glutes'),
('seated side crunch (wall)', 'waist', 'body weight', 'abs'),
('seated wide angle pose sequence', 'upper legs', 'body weight', 'hamstrings'),
('self assisted inverse leg curl', 'upper legs', 'body weight', 'hamstrings'),
('self assisted inverse leg curl (on floor)', 'upper legs', 'body weight', 'hamstrings'),
('semi squat jump (male)', 'cardio', 'body weight', 'cardiovascular system'),
('short stride run', 'cardio', 'body weight', 'cardiovascular system'),
('shoulder grip pull-up', 'back', 'body weight', 'lats'),
('shoulder tap', 'waist', 'body weight', 'abs'),
('shoulder tap push-up', 'chest', 'body weight', 'pectorals'),
('side bridge hip abduction', 'upper legs', 'body weight', 'abductors'),
('side bridge v. 2', 'waist', 'body weight', 'abs'),
('side hip (on parallel bars)', 'waist', 'body weight', 'abs'),
('side hip abduction', 'upper legs', 'body weight', 'abductors'),
('side lying floor stretch', 'back', 'body weight', 'lats'),
('side lying hip adduction (male)', 'upper legs', 'body weight', 'adductors'),
('side plank hip adduction', 'upper legs', 'body weight', 'adductors'),
('side push neck stretch', 'neck', 'body weight', 'levator scapulae'),
('side push-up', 'upper arms', 'body weight', 'triceps'),
('side wrist pull stretch', 'lower arms', 'body weight', 'forearms'),
('side-to-side chin', 'back', 'body weight', 'lats'),
('side-to-side toe touch (male)', 'waist', 'body weight', 'abs'),
('single arm push-up', 'chest', 'body weight', 'pectorals'),
('single leg bridge with outstretched leg', 'upper legs', 'body weight', 'glutes'),
('single leg calf raise (on a dumbbell)', 'lower legs', 'dumbbell', 'calves'),
('single leg platform slide', 'upper legs', 'body weight', 'hamstrings'),
('single leg squat (pistol) male', 'upper legs', 'body weight', 'glutes'),
('sissy squat', 'upper legs', 'body weight', 'quads'),
('sit-up v. 2', 'waist', 'body weight', 'abs'),
('sit-up with arms on chest', 'waist', 'body weight', 'abs'),
('skater hops', 'cardio', 'body weight', 'cardiovascular system'),
('ski ergometer', 'upper arms', 'skierg machine', 'triceps'),
('ski step', 'cardio', 'body weight', 'cardiovascular system'),
('skin the cat', 'back', 'body weight', 'upper back'),
('sled 45 degrees one leg press', 'upper legs', 'sled machine', 'glutes'),
('sled 45в° calf press', 'lower legs', 'sled machine', 'calves'),
('sled 45в° leg press', 'upper legs', 'sled machine', 'glutes'),
('sled 45в° leg press (back pov)', 'upper legs', 'sled machine', 'glutes'),
('sled 45° leg press (side pov)', 'upper legs', 'sled machine', 'glutes'),
('sled 45в° leg wide press', 'upper legs', 'sled machine', 'glutes'),
('sled calf press on leg press', 'lower legs', 'sled machine', 'calves'),
('sled closer hack squat', 'upper legs', 'sled machine', 'glutes'),
('sled forward angled calf raise', 'lower legs', 'sled machine', 'calves'),
('sled hack squat', 'upper legs', 'sled machine', 'glutes'),
('sled lying calf press', 'lower legs', 'sled machine', 'calves'),
('sled lying squat', 'upper legs', 'sled machine', 'glutes'),
('sled one leg calf press on leg press', 'lower legs', 'sled machine', 'calves'),
('sledge hammer', 'waist', 'hammer', 'abs'),
('smith back shrug', 'back', 'smith machine', 'traps'),
('smith behind neck press', 'shoulders', 'smith machine', 'delts'),
('smith bench press', 'chest', 'smith machine', 'pectorals'),
('smith bent knee good morning', 'upper legs', 'smith machine', 'glutes'),
('smith bent over row', 'back', 'smith machine', 'upper back'),
('smith chair squat', 'upper legs', 'smith machine', 'quads'),
('smith close-grip bench press', 'upper arms', 'smith machine', 'triceps'),
('smith deadlift', 'upper legs', 'smith machine', 'glutes'),
('smith decline bench press', 'chest', 'smith machine', 'pectorals'),
('smith decline reverse-grip press', 'chest', 'smith machine', 'pectorals'),
('smith front squat (clean grip)', 'upper legs', 'smith machine', 'glutes'),
('smith full squat', 'upper legs', 'smith machine', 'glutes'),
('smith hack squat', 'upper legs', 'smith machine', 'glutes'),
('smith hip raise', 'waist', 'smith machine', 'abs'),
('smith incline bench press', 'chest', 'smith machine', 'pectorals'),
('smith incline reverse-grip press', 'chest', 'smith machine', 'pectorals'),
('smith incline shoulder raises', 'chest', 'smith machine', 'serratus anterior'),
('smith leg press', 'upper legs', 'smith machine', 'glutes'),
('smith low bar squat', 'upper legs', 'smith machine', 'glutes'),
('smith machine bicep curl', 'upper arms', 'smith machine', 'biceps'),
('smith machine decline close grip bench press', 'upper arms', 'smith machine', 'triceps'),
('smith machine incline tricep extension', 'upper arms', 'smith machine', 'triceps'),
('smith machine reverse decline close grip bench press', 'chest', 'smith machine', 'pectorals'),
('smith narrow row', 'back', 'smith machine', 'upper back'),
('smith one arm row', 'back', 'smith machine', 'upper back'),
('smith one leg floor calf raise', 'lower legs', 'smith machine', 'calves'),
('smith rear delt row', 'shoulders', 'smith machine', 'delts'),
('smith reverse calf raises', 'lower legs', 'smith machine', 'calves'),
('smith reverse grip bent over row', 'back', 'smith machine', 'upper back'),
('smith reverse-grip press', 'chest', 'smith machine', 'pectorals'),
('smith seated one leg calf raise', 'lower legs', 'smith machine', 'calves'),
('smith seated shoulder press', 'shoulders', 'smith machine', 'delts'),
('smith seated wrist curl', 'lower arms', 'smith machine', 'forearms'),
('smith shoulder press', 'shoulders', 'smith machine', 'delts'),
('smith shrug', 'back', 'smith machine', 'traps')
ON CONFLICT (name) DO NOTHING;

INSERT INTO exercises (name, body_part, equipment, target) VALUES
('smith single leg split squat', 'upper legs', 'smith machine', 'quads'),
('smith sprint lunge', 'upper legs', 'smith machine', 'glutes'),
('smith squat', 'upper legs', 'smith machine', 'glutes'),
('smith standing back wrist curl', 'lower arms', 'smith machine', 'forearms'),
('smith standing behind head military press', 'shoulders', 'smith machine', 'delts'),
('smith standing leg calf raise', 'lower legs', 'smith machine', 'calves'),
('smith standing military press', 'shoulders', 'smith machine', 'delts'),
('smith sumo squat', 'upper legs', 'smith machine', 'glutes'),
('smith toe raise', 'lower legs', 'smith machine', 'calves'),
('smith upright row', 'shoulders', 'smith machine', 'delts'),
('smith wide grip bench press', 'chest', 'smith machine', 'pectorals'),
('smith wide grip decline bench press', 'chest', 'smith machine', 'pectorals'),
('snatch pull', 'upper legs', 'barbell', 'quads'),
('spell caster', 'waist', 'dumbbell', 'abs'),
('sphinx', 'back', 'body weight', 'spine'),
('spider crawl push up', 'upper legs', 'body weight', 'glutes'),
('spine stretch', 'back', 'body weight', 'spine'),
('spine twist', 'waist', 'body weight', 'abs'),
('split squats', 'upper legs', 'body weight', 'quads'),
('squat jerk', 'upper legs', 'barbell', 'quads'),
('squat on bosu ball', 'upper legs', 'bosu ball', 'quads'),
('squat to overhead reach', 'upper legs', 'body weight', 'quads'),
('squat to overhead reach with twist', 'upper legs', 'body weight', 'quads'),
('stability ball crunch (full range hands behind head)', 'waist', 'stability ball', 'abs'),
('stalder press', 'upper arms', 'body weight', 'triceps'),
('standing archer', 'back', 'body weight', 'upper back'),
('standing behind neck press', 'shoulders', 'barbell', 'delts'),
('standing calf raise (on a staircase)', 'lower legs', 'body weight', 'calves'),
('standing calves', 'lower legs', 'body weight', 'calves'),
('standing calves calf stretch', 'lower legs', 'body weight', 'calves'),
('standing hamstring and calf stretch with strap', 'upper legs', 'rope', 'hamstrings'),
('standing lateral stretch', 'back', 'body weight', 'lats'),
('standing pelvic tilt', 'back', 'body weight', 'spine'),
('standing single leg curl', 'upper legs', 'body weight', 'hamstrings'),
('standing wheel rollerout', 'waist', 'wheel roller', 'abs'),
('star jump (male)', 'cardio', 'body weight', 'cardiovascular system'),
('stationary bike run v. 3', 'cardio', 'stationary bike', 'cardiovascular system'),
('stationary bike walk', 'cardio', 'leverage machine', 'cardiovascular system'),
('straddle maltese', 'waist', 'body weight', 'abs'),
('straddle planche', 'waist', 'body weight', 'abs'),
('straight leg outer hip abductor', 'upper legs', 'body weight', 'abductors'),
('superman push-up', 'chest', 'body weight', 'pectorals'),
('suspended abdominal fallout', 'waist', 'body weight', 'abs'),
('suspended push-up', 'chest', 'body weight', 'pectorals'),
('suspended reverse crunch', 'waist', 'body weight', 'abs'),
('suspended row', 'back', 'body weight', 'upper back'),
('suspended split squat', 'upper legs', 'body weight', 'quads'),
('swimmer kicks v. 2 (male)', 'upper legs', 'body weight', 'glutes'),
('swing 360', 'cardio', 'body weight', 'cardiovascular system'),
('three bench dip', 'upper arms', 'body weight', 'triceps'),
('tire flip', 'upper legs', 'tire', 'glutes'),
('trap bar deadlift', 'upper legs', 'trap bar', 'glutes'),
('triceps dip', 'upper arms', 'body weight', 'triceps'),
('triceps dip (bench leg)', 'upper arms', 'body weight', 'triceps'),
('triceps dip (between benches)', 'upper arms', 'body weight', 'triceps'),
('triceps dips floor', 'upper arms', 'body weight', 'triceps'),
('triceps press', 'upper arms', 'body weight', 'triceps'),
('triceps stretch', 'upper arms', 'body weight', 'triceps'),
('tuck crunch', 'waist', 'body weight', 'abs'),
('twin handle parallel grip lat pulldown', 'back', 'cable', 'lats'),
('twist hip lift', 'upper legs', 'body weight', 'glutes'),
('twisted leg raise', 'waist', 'body weight', 'abs'),
('twisted leg raise (female)', 'waist', 'body weight', 'abs'),
('two toe touch (male)', 'back', 'body weight', 'spine'),
('upper back stretch', 'back', 'body weight', 'upper back'),
('upward facing dog', 'back', 'body weight', 'spine'),
('v-sit on floor', 'waist', 'body weight', 'abs'),
('vertical leg raise (on parallel bars)', 'waist', 'body weight', 'abs'),
('walk elliptical cross trainer', 'cardio', 'elliptical machine', 'cardiovascular system'),
('walking high knees lunge', 'cardio', 'body weight', 'cardiovascular system'),
('walking lunge', 'upper legs', 'body weight', 'glutes'),
('walking on incline treadmill', 'cardio', 'leverage machine', 'cardiovascular system'),
('walking on stepmill', 'cardio', 'stepmill machine', 'cardiovascular system'),
('weighted bench dip', 'upper arms', 'weighted', 'triceps'),
('weighted close grip chin-up on dip cage', 'back', 'weighted', 'lats'),
('weighted cossack squats (male)', 'upper legs', 'weighted', 'glutes'),
('weighted crunch', 'waist', 'weighted', 'abs'),
('weighted decline sit-up', 'waist', 'weighted', 'abs'),
('weighted donkey calf raise', 'lower legs', 'weighted', 'calves'),
('weighted drop push up', 'chest', 'weighted', 'pectorals'),
('weighted front plank', 'waist', 'weighted', 'abs'),
('weighted front raise', 'shoulders', 'weighted', 'delts'),
('weighted hanging leg-hip raise', 'waist', 'weighted', 'abs'),
('weighted hyperextension (on stability ball)', 'back', 'weighted', 'spine'),
('weighted kneeling step with swing', 'shoulders', 'weighted', 'delts'),
('weighted lunge with swing', 'upper legs', 'weighted', 'glutes'),
('weighted muscle up', 'back', 'weighted', 'lats'),
('weighted muscle up (on bar)', 'back', 'weighted', 'lats'),
('weighted one hand pull up', 'back', 'weighted', 'lats'),
('weighted overhead crunch (on stability ball)', 'waist', 'weighted', 'abs'),
('weighted pull-up', 'back', 'weighted', 'lats'),
('weighted round arm', 'shoulders', 'weighted', 'delts'),
('weighted russian twist', 'waist', 'weighted', 'abs'),
('weighted russian twist (legs up)', 'waist', 'weighted', 'abs'),
('weighted russian twist v. 2', 'waist', 'weighted', 'abs'),
('weighted seated bicep curl (on stability ball)', 'upper arms', 'medicine ball', 'biceps'),
('weighted seated twist (on stability ball)', 'waist', 'weighted', 'abs'),
('weighted side bend (on stability ball)', 'waist', 'weighted', 'abs'),
('weighted sissy squat', 'upper legs', 'weighted', 'quads'),
('weighted squat', 'upper legs', 'weighted', 'glutes'),
('weighted standing curl', 'upper arms', 'weighted', 'biceps'),
('weighted standing hand squeeze', 'lower arms', 'weighted', 'forearms'),
('weighted straight bar dip', 'chest', 'weighted', 'pectorals'),
('weighted stretch lunge', 'upper legs', 'weighted', 'glutes'),
('weighted svend press', 'chest', 'weighted', 'pectorals'),
('weighted three bench dips', 'upper arms', 'weighted', 'triceps'),
('weighted tricep dips', 'upper arms', 'weighted', 'triceps'),
('weighted triceps dip on high parallel bars', 'upper arms', 'weighted', 'triceps'),
('wheel rollerout', 'waist', 'wheel roller', 'abs'),
('wheel run', 'cardio', 'body weight', 'cardiovascular system'),
('wide grip pull-up', 'back', 'body weight', 'lats'),
('wide grip rear pull-up', 'back', 'body weight', 'lats'),
('wide hand push up', 'chest', 'body weight', 'pectorals'),
('wide-grip chest dip on high parallel bars', 'chest', 'body weight', 'pectorals'),
('wind sprints', 'waist', 'body weight', 'abs'),
('world greatest stretch', 'upper legs', 'body weight', 'hamstrings'),
('wrist circles', 'lower arms', 'body weight', 'forearms'),
('wrist rollerer', 'lower arms', 'weighted', 'forearms')
ON CONFLICT (name) DO NOTHING;
